-- MySQL Script generated by MySQL Workbench
-- 07/25/15 20:16:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema winchr
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `winchr` ;

-- -----------------------------------------------------
-- Schema winchr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `winchr` DEFAULT CHARACTER SET latin1 ;
USE `winchr` ;

-- -----------------------------------------------------
-- Table `winchr`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winchr`.`user` ;

CREATE TABLE IF NOT EXISTS `winchr`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(100) NOT NULL COMMENT '',
  `openid` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `forename` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `surname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `sex` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `usercol` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `dob` DATE NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(155) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `winchr`.`contact_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winchr`.`contact_info` ;

CREATE TABLE IF NOT EXISTS `winchr`.`contact_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `value` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `unique_id` (`id` ASC)  COMMENT '',
  INDEX `fk_contact_info_user_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_contact_info_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `winchr`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `winchr`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winchr`.`event` ;

CREATE TABLE IF NOT EXISTS `winchr`.`event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `location` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `date` DATE NULL DEFAULT NULL COMMENT '',
  `time` TIME NULL DEFAULT NULL COMMENT '',
  `host` INT(11) NULL DEFAULT NULL COMMENT '',
  `spaces` INT(11) NULL DEFAULT NULL COMMENT '',
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `unique_id` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `winchr`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winchr`.`match` ;

CREATE TABLE IF NOT EXISTS `winchr`.`match` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `match_id` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `event_id` INT(11) NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `event_id`, `user_id`)  COMMENT '',
  UNIQUE INDEX `unique_id` (`id` ASC)  COMMENT '',
  INDEX `fk_match_event1_idx` (`event_id` ASC)  COMMENT '',
  INDEX `fk_match_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_match_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `winchr`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `winchr`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `winchr`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winchr`.`registration` ;

CREATE TABLE IF NOT EXISTS `winchr`.`registration` (
  `id` INT(11) NOT NULL COMMENT '',
  `event_id` INT(11) NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_registration_event1_idx` (`event_id` ASC)  COMMENT '',
  INDEX `fk_registration_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_registration_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `winchr`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registration_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `winchr`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
