-- MySQL Script generated by MySQL Workbench
-- 08/08/15 10:43:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(100) NOT NULL COMMENT '',
  `openid` VARCHAR(100) NULL COMMENT '',
  `forename` VARCHAR(45) NULL COMMENT '',
  `surname` VARCHAR(45) NULL COMMENT '',
  `sex` VARCHAR(10) NULL COMMENT '',
  `usercol` VARCHAR(45) NULL COMMENT '',
  `dob` DATE NULL COMMENT '',
  `password` VARCHAR(155) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `contact_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact_info` ;

CREATE TABLE IF NOT EXISTS `contact_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  `value` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `unique_id` (`id` ASC)  COMMENT '',
  INDEX `fk_contact_info_user_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_contact_info_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event` ;

CREATE TABLE IF NOT EXISTS `event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `location` VARCHAR(45) NULL COMMENT '',
  `date` DATE NULL COMMENT '',
  `time` TIME NULL COMMENT '',
  `host` INT(11) NULL COMMENT '',
  `spaces` INT NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `unique_id` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `match` ;

CREATE TABLE IF NOT EXISTS `match` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `match_id` VARCHAR(45) NULL COMMENT '',
  `event_id` INT(11) NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `event_id`, `user_id`)  COMMENT '',
  UNIQUE INDEX `unique_id` (`id` ASC)  COMMENT '',
  INDEX `fk_match_event1_idx` (`event_id` ASC)  COMMENT '',
  INDEX `fk_match_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_match_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registration` ;

CREATE TABLE IF NOT EXISTS `registration` (
  `id` INT NOT NULL COMMENT '',
  `event_id` INT(11) NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_registration_event1_idx` (`event_id` ASC)  COMMENT '',
  INDEX `fk_registration_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_registration_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registration_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
